# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: IrChad
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - pymdownx.blocks.caption

plugins:
  - search:
      enabled: false
repo_url: https://github.com/usrbinsam/irchad
repo_name: usrbinsam/irchad

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra_javascript:
  - js/downloads.js
