// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Config {
    "name": string;
    "irc": IRCConfig;
    "live": LiveConfig;
    "auth": string;
}

export interface IRCConfig {
    "server": string;
}

export interface LiveConfig {
    "server": string;
}

export interface Network {
    "DiscoveryURL": string;
    "Config": Config | null;
    "AccountName": string;
    "Nick": string;
}
