// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Connect(discoveryURL: string, nick: string, accountName: string, passphrase: string): $CancellablePromise<$models.Config | null> {
    return $Call.ByID(3343847564, discoveryURL, nick, accountName, passphrase);
}

export function Get(discoveryURL: string): $CancellablePromise<$models.Network | null> {
    return $Call.ByID(509727082, discoveryURL);
}

export function GetJoinToken(discoveryURL: string, channelName: string): $CancellablePromise<string> {
    return $Call.ByID(3076341027, discoveryURL, channelName);
}
