// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as live$0 from "../../../../../IrChad/internal/live/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "live:participant-connected": live$0.ParticipantConnected;
            "live:participant-dissconnected": live$0.ParticipantDisconnected;
            "live:participant-track-published": live$0.ParticipantTrackPublished;
        }
    }
}
