//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as live$0 from "../../../../../IrChad/internal/live/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "live:participant-connected": $$createType0,
        "live:participant-dissconnected": $$createType1,
        "live:participant-track-published": $$createType2,
    }));
}

// Private type creation functions
const $$createType0 = live$0.ParticipantConnected.createFrom;
const $$createType1 = live$0.ParticipantDisconnected.createFrom;
const $$createType2 = live$0.ParticipantTrackPublished.createFrom;

configure();
