// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * @param {string} channelName
 * @returns {$CancellablePromise<void>}
 */
export function Connect(channelName) {
    return $Call.ByID(1257987059, channelName);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function Connected() {
    return $Call.ByID(2850702642);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Disconnect() {
    return $Call.ByID(4255897781);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function PublishWebcam() {
    return $Call.ByID(2617723007);
}
