// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} nick
 * @param {string} channelName
 * @returns {$CancellablePromise<void>}
 */
export function Connect(nick, channelName) {
    return $Call.ByID(1257987059, nick, channelName);
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function Connected() {
    return $Call.ByID(2850702642);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function Disconnect() {
    return $Call.ByID(4255897781);
}

/**
 * @returns {$CancellablePromise<$models.WindowData[]>}
 */
export function GetWindows() {
    return $Call.ByID(4015795614).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function PublishMicrophone() {
    return $Call.ByID(762739442);
}

/**
 * @param {number} ID
 * @param {$models.ScreenShareOpts} ss
 * @returns {$CancellablePromise<void>}
 */
export function PublishScreenShare(ID, ss) {
    return $Call.ByID(2179788497, ID, ss);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function PublishWebcam() {
    return $Call.ByID(2617723007);
}

/**
 * @param {boolean} muted
 * @returns {$CancellablePromise<void>}
 */
export function SetMicMuted(muted) {
    return $Call.ByID(1982595911, muted);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function UnpublishMicrophone() {
    return $Call.ByID(937473251);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function UnpublishScreenShare() {
    return $Call.ByID(2171747118);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function UnpublishWebcam() {
    return $Call.ByID(1463901962);
}

// Private type creation functions
const $$createType0 = $models.WindowData.createFrom;
const $$createType1 = $Create.Array($$createType0);
