// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ParticipantConnected {
    /**
     * Creates a new ParticipantConnected instance.
     * @param {Partial<ParticipantConnected>} [$$source = {}] - The source object to create the ParticipantConnected.
     */
    constructor($$source = {}) {
        if (!("Identity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Identity"] = "";
        }
        if (!("Channel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Channel"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ParticipantConnected instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ParticipantConnected}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ParticipantConnected(/** @type {Partial<ParticipantConnected>} */($$parsedSource));
    }
}

export class ParticipantDisconnected {
    /**
     * Creates a new ParticipantDisconnected instance.
     * @param {Partial<ParticipantDisconnected>} [$$source = {}] - The source object to create the ParticipantDisconnected.
     */
    constructor($$source = {}) {
        if (!("Identity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Identity"] = "";
        }
        if (!("Channel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Channel"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ParticipantDisconnected instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ParticipantDisconnected}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ParticipantDisconnected(/** @type {Partial<ParticipantDisconnected>} */($$parsedSource));
    }
}

export class ParticipantTrackPublished {
    /**
     * Creates a new ParticipantTrackPublished instance.
     * @param {Partial<ParticipantTrackPublished>} [$$source = {}] - The source object to create the ParticipantTrackPublished.
     */
    constructor($$source = {}) {
        if (!("Identity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Identity"] = "";
        }
        if (!("TrackID" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["TrackID"] = "";
        }
        if (!("SubscribeURL" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["SubscribeURL"] = "";
        }
        if (!("Source" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Source"] = "";
        }
        if (!("Kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["Kind"] = "";
        }
        if (!("Show" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["Show"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ParticipantTrackPublished instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ParticipantTrackPublished}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ParticipantTrackPublished(/** @type {Partial<ParticipantTrackPublished>} */($$parsedSource));
    }
}
