// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function Connect(nick: string, channelName: string): $CancellablePromise<void> {
    return $Call.ByID(1257987059, nick, channelName);
}

export function Connected(): $CancellablePromise<boolean> {
    return $Call.ByID(2850702642);
}

export function Disconnect(): $CancellablePromise<void> {
    return $Call.ByID(4255897781);
}

export function GetWindows(): $CancellablePromise<$models.WindowData[] | null> {
    return $Call.ByID(4015795614);
}

export function PublishMicrophone(): $CancellablePromise<void> {
    return $Call.ByID(762739442);
}

export function PublishScreenShare(ID: number, ss: $models.ScreenShareOpts): $CancellablePromise<void> {
    return $Call.ByID(2179788497, ID, ss);
}

export function PublishWebcam(): $CancellablePromise<void> {
    return $Call.ByID(2617723007);
}

export function SetMicMuted(muted: boolean): $CancellablePromise<void> {
    return $Call.ByID(1982595911, muted);
}

export function SetParticipantVolume(participantID: string, vol: number): $CancellablePromise<void> {
    return $Call.ByID(298078976, participantID, vol);
}

export function UnpublishMicrophone(): $CancellablePromise<void> {
    return $Call.ByID(937473251);
}

export function UnpublishScreenShare(): $CancellablePromise<void> {
    return $Call.ByID(2171747118);
}

export function UnpublishWebcam(): $CancellablePromise<void> {
    return $Call.ByID(1463901962);
}
