// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

export function Connect(channelName: string): $CancellablePromise<void> {
    return $Call.ByName("IrChad/internal/live.LiveChat.Connect", channelName);
}

export function Connected(): $CancellablePromise<boolean> {
    return $Call.ByName("IrChad/internal/live.LiveChat.Connected");
}

export function Disconnect(): $CancellablePromise<void> {
    return $Call.ByName("IrChad/internal/live.LiveChat.Disconnect");
}

export function PublishMicrophone(): $CancellablePromise<void> {
    return $Call.ByName("IrChad/internal/live.LiveChat.PublishMicrophone");
}

export function PublishWebcam(): $CancellablePromise<void> {
    return $Call.ByName("IrChad/internal/live.LiveChat.PublishWebcam");
}
