// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ParticipantConnected {
    "Identity": string;
    "Channel": string;

    /** Creates a new ParticipantConnected instance. */
    constructor($$source: Partial<ParticipantConnected> = {}) {
        if (!("Identity" in $$source)) {
            this["Identity"] = "";
        }
        if (!("Channel" in $$source)) {
            this["Channel"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ParticipantConnected instance from a string or object.
     */
    static createFrom($$source: any = {}): ParticipantConnected {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ParticipantConnected($$parsedSource as Partial<ParticipantConnected>);
    }
}

export class ParticipantDisconnected {
    "Identity": string;
    "Channel": string;

    /** Creates a new ParticipantDisconnected instance. */
    constructor($$source: Partial<ParticipantDisconnected> = {}) {
        if (!("Identity" in $$source)) {
            this["Identity"] = "";
        }
        if (!("Channel" in $$source)) {
            this["Channel"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ParticipantDisconnected instance from a string or object.
     */
    static createFrom($$source: any = {}): ParticipantDisconnected {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ParticipantDisconnected($$parsedSource as Partial<ParticipantDisconnected>);
    }
}

export class ParticipantTrackPublished {
    "Identity": string;
    "TrackID": string;
    "SubscribeURL": string;
    "Source": string;
    "Kind": string;
    "Show": boolean;

    /** Creates a new ParticipantTrackPublished instance. */
    constructor($$source: Partial<ParticipantTrackPublished> = {}) {
        if (!("Identity" in $$source)) {
            this["Identity"] = "";
        }
        if (!("TrackID" in $$source)) {
            this["TrackID"] = "";
        }
        if (!("SubscribeURL" in $$source)) {
            this["SubscribeURL"] = "";
        }
        if (!("Source" in $$source)) {
            this["Source"] = "";
        }
        if (!("Kind" in $$source)) {
            this["Kind"] = "";
        }
        if (!("Show" in $$source)) {
            this["Show"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ParticipantTrackPublished instance from a string or object.
     */
    static createFrom($$source: any = {}): ParticipantTrackPublished {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ParticipantTrackPublished($$parsedSource as Partial<ParticipantTrackPublished>);
    }
}

export class WindowData {
    "ID": number;
    "Title": string;
    "X": number;
    "Y": number;
    "W": number;
    "H": number;

    /** Creates a new WindowData instance. */
    constructor($$source: Partial<WindowData> = {}) {
        if (!("ID" in $$source)) {
            this["ID"] = 0;
        }
        if (!("Title" in $$source)) {
            this["Title"] = "";
        }
        if (!("X" in $$source)) {
            this["X"] = 0;
        }
        if (!("Y" in $$source)) {
            this["Y"] = 0;
        }
        if (!("W" in $$source)) {
            this["W"] = 0;
        }
        if (!("H" in $$source)) {
            this["H"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WindowData instance from a string or object.
     */
    static createFrom($$source: any = {}): WindowData {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WindowData($$parsedSource as Partial<WindowData>);
    }
}
