// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export type FrameRate = number;

export interface ParticipantConnected {
    "Identity": string;
    "Channel": string;
}

export interface ParticipantDisconnected {
    "Identity": string;
    "Channel": string;
}

export interface ParticipantTrackPublished {
    "Identity": string;
    "TrackID": string;
    "SubscribeURL": string;
    "Source": string;
    "Kind": string;
    "Show": boolean;
    "TrackName": string;
}

export interface ParticipantTrackUnpublished {
    "Identity": string;
    "TrackID": string;
}

export interface ScreenShareClosed {
}

export interface ScreenShareOpts {
    "FrameRate": FrameRate;
    "BitRate": number;
}

export interface SpeakingChanged {
    "Identity": string;
    "IsSpeaking": boolean;
}

export interface WindowData {
    "ID": number;
    "Title": string;
    "X": number;
    "Y": number;
    "W": number;
    "H": number;
    "PID": number;
    "WMClass": string;
    "MonitorIndex": number;
}
