name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: windows

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        if: matrix.platform == 'linux'
        with:
          go-version: "1.26"
          cache-dependency-path: app/go.sum

      - name: Setup Node.js
        uses: actions/setup-node@v4
        if: matrix.platform == 'linux'
        with:
          node-version: 24

      - name: Install Linux dependencies
        if: matrix.platform == 'linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev build-essential pkg-config \
            libgstreamer1.0-dev \
            libgstreamer-plugins-base1.0-dev \
            libgstreamer-plugins-good1.0-dev \
            libgstreamer-plugins-bad1.0-dev \
            gstreamer1.0-plugins-ugly \
            gstreamer1.0-plugins-rtp \
            gstreamer1.0-plugins-base-apps \
            gstreamer1.0-pipewire

      - name: Setup MSYS2
        if: matrix.platform == 'windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          path-type: "minimal"
          install: >-
            mingw-w64-x86_64-crt-git
            mingw-w64-x86_64-binutils
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-gdb
            mingw-w64-x86_64-gdb-multiarch
            mingw-w64-x86_64-go
            mingw-w64-x86_64-headers-git
            mingw-w64-x86_64-libmangle-git
            mingw-w64-x86_64-libwinpthread
            mingw-w64-x86_64-make
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-tools-git
            mingw-w64-x86_64-winpthreads
            mingw-w64-x86_64-gstreamer
            mingw-w64-x86_64-gst-plugins-base
            mingw-w64-x86_64-gst-plugins-good
            mingw-w64-x86_64-gst-plugins-bad
            mingw-w64-x86_64-gst-plugins-rs
            mingw-w64-x86_64-gst-plugins-ugly
            mingw-w64-x86_64-gst-libav
            mingw-w64-x86_64-nodejs

      - name: Install Wails v3 CLI
        shell: bash
        run: |
          go install github.com/wailsapp/wails/v3/cmd/wails3@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Build Application
        working-directory: app/
        shell: bash
        run: |
          wails3 generate bindings -d frontend/src/bindings -ts -names
          wails3 build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wails-app-${{ matrix.platform }}
          path: |
            app/bin/*
